export const PROPOSALS_LOADING = 'PROPOSALS_LOADING';
export const ADD_PROPOSALS = 'ADD_PROPOSALS';
export const PROPOSALS_FAILED = 'PROPOSALS_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const IDEAS_LOADING = 'IDEAS_LOADING';
export const ADD_IDEAS = 'ADD_IDEAS';
export const IDEAS_FAILED = 'IDEAS_FAILED';

export const PARTNERS_LOADING = 'PARTNERS_LOADING';
export const ADD_PARTNERS = 'ADD_PARTNERS';
export const PARTNERS_FAILED = 'PARTNERS_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';

export const ADD_COMMENT = 'ADD_COMMENT';

export const DELETE_FAVORITE = 'DELETE_FAVORITE'; 